extends:
  - eslint:recommended
  - plugin:import/typescript
  - plugin:import/recommended
  - plugin:vue/vue3-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:promise/recommended
parserOptions:
  project: './tsconfig.json'
  extraFileExtensions: [ '.vue' ]
  tsconfigRootDir: .
  parser:
    ts: '@typescript-eslint/parser'
parser: vue-eslint-parser
env:
  browser: true
  es2021: true
overrides: [ ]
rules: { }
