spring:
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
    validate-migration-naming: true
  webflux:
    base-path: /api
